### ISSUE TITLE
In which part of the program did you use chatgpt?

### ISSUE THREAD

**Issue by kazemsamiei** [r57-labs/chaos#7]
Hi
Where did you use chatgpt in the program?
I do not see anything.

**Comment by r57labs** [comment]
Hello kazemsamiei,

Please excuse any confusion, ChatGPT was used to assist in the rapid development of this software from idea to prototype to release.

This utility does not actively use the ChatGPT API for functionality.

If you have interest in using ChatGPT to improve your ability to write software and scripts, then please keep an eye out on our website at: https://r57labs.com/

Otherwise, thank you for your question and interest.  Please stay tuned for future releases, and take care!
